django_tutorial/src/djangoTut/djangoTut/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve
from django.conf.urls import url
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

django_tutorial/src/djangoTut/polls/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('bonus/', views.BonusView.as_view(), name='bonus'),
    path('create-question/',views.QuestionCreate.as_view(), name = 'questioncreate'),
    path('<int:pk>/delete-question/',views.QuestionDelete.as_view(), name = 'questiondel'),
    path('<int:pk>/add-choice/',views.AddChoice.as_view(), name = 'choiceadd'),
    path('login/', views.CustomLoginView.as_view(), name = 'login'),
    path('logout/', LogoutView.as_view(next_page = 'polls:index'), name = 'logout'),
]

django_tutorial/src/djangoTut/polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField(auto_now_add= True)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, null=True, blank=True)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

django_tutorial/src/djangoTut/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.urls.base import reverse_lazy
from django.views import generic
from django.views.generic.edit import CreateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin

from django.http import HttpResponse, Http404, HttpResponseRedirect

from .models import Question, Choice
from django.contrib.auth.views import LoginView

# def index (request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     output = ', '.join([q.question_text for q in latest_question_list])

#     context = {
#         'latest_question_list': latest_question_list,
#     }

    # return render(request, 'polls/index.html', context)

class CustomLoginView(LoginView):
    template_name = 'polls/login.html'
    fields = '__all__'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('polls:index')

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:10]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

class BonusView(generic.ListView):
    template_name = 'polls/bonus.html'
    context_object_name = 'question_list'

    def get_queryset(self):

        return Question.objects.order_by('-pub_date')

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
    
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
  
        return HttpResponseRedirect(reverse('polls:index'))

class QuestionCreate(LoginRequiredMixin, CreateView):
    model = Question
    fields = '__all__' 
    success_url = reverse_lazy('polls:index')
    template_name = 'polls/questioncreate.html' 
    context_object_name = 'question'

class QuestionDelete(LoginRequiredMixin, DeleteView):
    model = Question
    template_name = 'polls/questiondelete.html'
    context_object_name = 'question'
    success_url = reverse_lazy('polls:index')
    def delete(self, *args, **kwargs):
       
        return super().delete(*args, **kwargs)

class AddChoice(LoginRequiredMixin, CreateView):
    model = Choice
    fields = ['choice_text', 'question']
    template_name = 'polls/choiceadd.html'
    success_url = reverse_lazy('polls:index')

    

    
    

django_tutorial/src/djangoTut/polls/templates/polls/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    
    <title>Strange Survey </title>
    <style>
        body {
          background-color: rgb(245, 243, 245);
          font-family: "courier new", monospace;
          padding-top: 0px;
        }

        .container {
        max-width: 1000px;
        padding-top: 20px;
        margin: auto;
        background-color: rgb(237, 243, 245);
        -webkit-box-shadow: 2px 2px 13px -4px rgba(0, 0, 0, 0.21);
        box-shadow: 2px 2px 13px -4px rgba(0, 0, 0, 0.21);
        padding-bottom: 50px;
        border-radius: 10px;
        }

        .header-bar {
        /* display: flex; */
        justify-content: space-between;
        color: rgb(24, 16, 16);
        padding: 10px;
        border-radius: 5px 5px 0 0;
        background:wheat;
      }

      #quest {
        background-color: #cacaac;
        color: rgb(34, 22, 22);
        font-size: 25px;
        border: #121314 1px solid;
        padding-left: 10px;
        border-radius: 10px;
        padding-bottom: 5px;
      }
      input[type = radio]{
        border: 5px;
        width: 2em;
        height: 2em;
      }
      #answers {
        
        text-transform: capitalize;
        color: rgb(10, 5, 2);
        font-size: 20px;
        font-family: "monaco", monospace;
        }

      .quest-wrapper {
        /* display: flex; */
        align-items: center; 
        justify-content: space-between;
        background-color: rgb(241, 226, 226);
        border-top: 1px solid #121314;
        overflow: hidden;
        
      }

      .delete {
        text-decoration: none;
        font-weight: 700;
        color: #cf4949;
        font-size: 30px;
        line-height: 0;
        padding: 30px 0px;
      }

      #choices-wrapper {
        display: flex;
        background-color: rgb(226, 94, 71);
        padding: 20px;
      }

      #add-link {
        color: #eb796f;
        text-decoration: none;
        font-size: 42px;
        text-shadow: 1px 1px #81413b;
      }

      #button {
      float: right;
      background-color: #4CAF50;
      border-radius: 10px;
      color: white;
      padding: 5px 5px;
      text-align: center;
      text-decoration: none;
      display: inline-block;
      font-size: 20px;
      }
      .btn_a{
        background-color: blue;

      }
      /* .buttona{
        line-height: 50px;
        
        position: relative;;
        padding: 10px;
      } */

     

      nav{ 
        background-color: rgb(223, 185, 154);
        height: 80px;
        width: 100%;
        font-family:Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;
      }

      label.logo{
        color: rgb(31, 27, 27);
        font-size: 35px;
        line-height: 80px;
        padding: 0 100px;
        font-weight: bold;
      }

      nav ul{
        float: right;
        margin-right: 20px;
        
      }

      nav ul li{
        display: inline-block;
        line-height: 80px;
        margin: 0 5px;
      }

      b li{
        line-height: 50px;
        padding-top: 20px;
      }

      nav ul li a{
        color: rgb(26, 19, 19);
        font-size: 20px;
        text-transform: uppercase;
      }

      input[type=submit] {
        width: 5em;  
        height: 5em;
        font-size: 15px;
    
      }

    </style>
  </head>

  <body>
    <nav>
      <label class = 'logo'> Poll Application </label>
      <ul>
        <li> <a href = "{%url 'polls:index' %}"> Home </a></li>
        {% if request.user.is_authenticated %}
        <li> <a href = "{%url 'polls:logout' %}"> logout </a></li>
        <li> <a href = "{%url 'polls:questioncreate' %}"> create </a></li>
        {% else %}
        <li> <a href = "{%url 'polls:login' %}"> login </a></li>
        {%endif%}
      </ul>
      
    </nav>

    <div class="container">{% block content %} {% endblock content %}</div>
  </body>
</html>

django_tutorial/src/djangoTut/polls/templates/polls/bonus.html
{% extends 'polls/base.html' %} {% block content %}

<div class="header-bar">
    <div>
        <h1>Hello {{request.user|title}}</h1>
        <h3 style="margin:0">Here is the Results of the Poll </h3>
    </div>
</div>
{% if question_list %}
    <ol>
  

    {% for question in question_list %}
        <div id = "quest"> 
            <li> <h4> {{ question.question_text }} </h4></li> 
        </div>

            <ul> 
                {% for choice in question.choice_set.all %}
                <div id = "answers">
                    <li> <h5 >{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</h5> </li>
                </div>
      
                {% endfor %}
            </ul>
    {% endfor %}
   
    </ol>




{% else %}
    <p>No polls are available.</p>
{% endif %}

{% endblock content %}

django_tutorial/src/djangoTut/polls/templates/polls/choiceadd.html
{% extends 'polls/base.html' %} {% block content %}

<div class="header-bar">
    <h1> Add a choice to the poll </h1>
</div>

<div class="quest-wrapper">
    <form method="POST" action="">
        {% csrf_token %}
        <div id = 'quest'>{{form.as_p}} </div>
        <p>
        <input class="button" type="submit" value="Submit">
    </form>
</div>

<a href="{% url 'polls:index' %}" style='font-size:60px;'>&#8617;</a>

{% endblock content %}

django_tutorial/src/djangoTut/polls/templates/polls/detail.html
{% extends 'polls/base.html' %} {% block content %}

{% if request.user.is_authenticated %}
<a id="add-link" href="{% url 'polls:choiceadd' pk=question.pk %}">&#x2b;</a>
{%endif%}

<div class= 'header-bar' > 
    <h1>{{ question.question_text }}</h1>
</div>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}

<div class = 'quest-wrapper'>
{% for choice in question.choice_set.all %}
<div id="quest">
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
</div>
{% endfor %} 


<!-- <p> </p> -->
<input id = "button" type="submit" value="Vote"> 
</form>
</div>
<a href="{% url 'polls:index' %}" style='font-size:60px;'>&#8617;</a>

{% endblock content %}

django_tutorial/src/djangoTut/polls/templates/polls/index.html
{% extends 'polls/base.html' %} {% block content %}
{% if latest_question_list %}

<div class="header-bar">

        <h1>Available Polls</h1>
        <!-- <P></P>
        <h3> please click the bellow questions to answer them. </h3> -->

</div>
    
<div id="questionlist" class="quest-wrapper">
    <ol>
    {% for question in latest_question_list %}
    <div id="quest"> <b><li>{{ question.question_text }}</li></b>
        
        <!-- <a class="delete" href="{% url 'polls:questiondel' pk=question.pk %}"> &#215;</a> -->

        <span class ='button_a'>
            <a id = 'button' href="{% url 'polls:detail' question.id %}" class="btn ">Vote</a> &nbsp;
            <a id = 'button' href="{% url 'polls:results' question.id %}" class="btn_a">View Results</a> &nbsp;
        </span>
    </div>
    
    {% endfor %}
    </ol>
</div>



{% else %}
    <p>No polls are available.</p>
{% endif %}

<h3><a href="{%url 'polls:bonus' %}"> go to polls result. </a> </h3> 



{% endblock content %}

django_tutorial/src/djangoTut/polls/templates/polls/login.html
{% extends 'polls/base.html' %}
{% block content %}

<div class="header-bar">
    <h1>Login</h1>
</div>

<div class="card-body">
    <form method="POST">
        {% csrf_token %}
        <div id = 'quest'>{{form.as_p}} </div>
        <p></p>
        <input class="button" type="submit" value="Login">
    </form>
   
</div>


{% endblock content %}

django_tutorial/src/djangoTut/polls/templates/polls/questioncreate.html
{% extends 'polls/base.html' %} {% block content %}

<div class="header-bar">
    <h1> Create a new Poll </h1>
</div>

<div class="quest-wrapper">
    <form method="POST" action="{% url 'polls:questioncreate' %}">
        {% csrf_token %}
        <div id = 'quest'>{{form.as_p}} </div>
        <p>
        <input class="button" type="submit" value="Submit">
    </form>
</div>

<a href="{% url 'polls:index' %}" style='font-size:60px;'>&#8617;</a>

{% endblock content %}

django_tutorial/src/djangoTut/polls/templates/polls/questiondelete.html
<div class="card-body">
    <form method="POST">
        {% csrf_token %}
        <p>Are your sure you want to delete this question? "{{question}}"</p>
        <input class="button" type="submit" value="Delete" />
    </form>
</div>

django_tutorial/src/djangoTut/polls/templates/polls/results.html
{% extends 'polls/base.html' %} {% block content %}

<div class = 'header-bar'> <h1>{{ question.question_text }}</h1> </div>

<div class = 'quest-wrapper'> 


{% for choice in question.choice_set.all %} 
<div id = 'quest'>
    <b><p>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</p></b>
</div>
{% endfor %}

</div>

<a href="{% url 'polls:index' %}" style='font-size:60px;'>&#8617;</a>

{% endblock content %}